en: "en"
vi: "vi"
user:
  validates:
    max_name_length: 30
    max_email_length: 30
    min_pass_length: 6
  gravatar_size: 80
  gravatar_size_small: 50
  gravatar_post_size: 42
  gender:
    male: "Male"
    female: "Female"
remember_box:
  is_checked: "1"
list_user:
  num_user_per_page: "6"
num_user_per_page: "6"
num_feeds_per_page: "6"
reaction_type:
  like: 1
